# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 240fa90702b3a814529912c4cd0e332d2f1a7dff0c60d2a82c0eac3b894dbfae1449565162ca4b5530e924596636203e58302bd0d3d2ace842bc344da4d3f901

test:
  secret_key_base: a8158a71a96ec47119e2ba7b0ab921701d5ba76e5d9d7df1277db0382738757db4dbb6d98331df4b7dbfcc495aead5680d33a06ef83685c25a9c51dff0f9b5af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
